- name: Ensure system doesn't do update checks in the background
  systemd:
    enabled: false
    state: stopped
    name: "{{ item }}"
  with_items:
    - 'unattended-upgrades.service'
    - 'apt-daily.service'
    - 'apt-daily.timer'
    - 'apt-daily-upgrade.service'
    - 'apt-daily-upgrade.timer'
