---
- include_role:
    name: "{{ test_subject }}"
  vars:
    action: start

- name: sleep for 15 seconds to let {{ test_subject }} boot
  wait_for:
    timeout: 15

- name: Log test data from the container
  include_role:
    name: test_docker_container
  vars:
    action: start

- name: sleep for 15 seconds to let docker and {{ test_subject }} catch up
  wait_for:
    timeout: 15

- name: Remove test container
  include_role:
    name: test_docker_container
  vars:
    action: remove

- include_role:
    name: "{{ test_subject }}"
  vars:
    action: stop
