---
- name: Setup the journald configuration directory
  file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: 0755

- name: Install journald rate limits configurations
  copy:
    src: journald_rate_limits.conf
    dest: /etc/systemd/journald.conf.d/filesize.conf
    mode: 0644
    remote_src: no
