---
- name: Setup the telegraf user
  user:
    name: telegraf
    createhome: no
    home: /opt/telegraf
    shell: /usr/sbin/nologin

- name: "Downloading Telegraf ({{ version }})"
  get_url:
    url: "https://dl.influxdata.com/telegraf/releases/telegraf_{{ version }}_amd64.deb"
    dest: /tmp/telegraf.deb
    mode: 0644

- name: Install Telegraf
  shell: dpkg -i /tmp/telegraf.deb

- name: Remove Telegraf archive
  file:
    path: /tmp/telegraf.deb
    state: absent

- name: Install Telegraf configuration
  template:
    src: "{{ configuration_file }}"
    dest: /etc/telegraf/telegraf.conf
    mode: 0644

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the telegraf service is stopped
  systemd:
    name: telegraf
    daemon_reload: yes
    enabled: no
    state: stopped
