---
- import_playbook: reset.yml

- hosts: '{{ test_namespace }}:&tag_TestRole_subject'
  become: true
  tasks:
    - name: Remove previous test log files
      shell: rm -rf {{ test_file_location }}*

    - name: Create a test log file
      shell: echo "First line" > {{ test_file_location }}

    - name: Change test file permissions
      file:
        path: "{{ test_file_location }}"
        owner: root
        group: root
        mode: '0774'

    - name: Start test servers
      include_role:
        name: test_servers
      vars:
        action: start

    - name: Start {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: start

    - name: Wait 30 seconds
      pause:
        seconds: 30

    - name: Rotate file with new data
      shell: |
        mv {{ test_file_location }} {{ test_file_location }}0
        echo "New file line" > {{ test_file_location }}
        sleep 5
        echo "Last line" >> {{ test_file_location }}0

    - name: Wait 10 seconds
      pause:
        seconds: 10

    - name: Stop {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: stop

    - name: Stop test servers
      include_role:
        name: test_servers
      vars:
        action: stop

    - name: Capture summary
      include: "capture_summary/{{ test_subject }}.yml"

    - debug:
        var: summary

    - assert:
        that:
          - summary.message_count == 3
