---
# Python is required in order to run the AWS command line tool
- name: Install Python 3
  apt:
    name: python3
    state: present

# pip is required in order to install the AWS command line tool
- name: Install Python pip 3
  apt:
    name: python3-pip
    state: present

- name: Install Python 2/3 setuptools
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-setuptools
    - python3-setuptools

- name: Install boto3 for Ansible
  pip:
    name: boto3
    executable: pip3
