---
- include_role:
    name: heka
  vars:
    action: install
    version: "{{ preinstalled_heka_version }}"

- include_role:
    name: openheka
  vars:
    action: install
    version: "{{ preinstalled_openheka_version }}"

- include_role:
    name: aixagent
  vars:
    action: install
    version: "{{ preinstalled_aixagent_version }}"

- include_role:
    name: nxlog
  vars:
    action: install
    version: "{{ preinstalled_nxlog_version }}"

- include_role:
    name: rsyslog
  vars:
    action: install

- include_role:
    name: syslog-ng
  vars:
    action: install

- include_role:
    name: vector
  vars:
    action: install
    version: "{{ preinstalled_vector_version }}"

- include_role:
    name: filebeat
  vars:
    action: install
    version: "{{ preinstalled_filebeat_version }}"

- include_role:
    name: fluentbit
  vars:
    action: install
    version: "{{ preinstalled_fluentbit_version }}"

- include_role:
    name: fluentd
  vars:
    action: install
    version: "{{ preinstalled_fluentd_version }}"

- include_role:
    name: logstash
  vars:
    action: install
    version: "{{ preinstalled_logstash_version }}"

- include_role:
    name: splunk_heavy_forwarder
  vars:
    action: install
    version_with_hash: "{{ preinstalled_splunk_heavy_forwarder_version }}"

- include_role:
    name: splunk_universal_forwarder
  vars:
    action: install
    version_with_hash: "{{ preinstalled_splunk_universal_forwarder_version }}"

# - include_role:
#     name: subjects
#   vars:
#     action: save_facts
