[sources.in]
  type               = "file"
  include            = ["{{ test_files_root }}*.log"]
  read_from          = "beginning"

[sinks.out]
  inputs  = ["in"]
  type    = "socket"
  mode    = "tcp"
  encoding.codec = "text"
  address = "{{ consumer_ip }}:{{ consumer_port }}"
