---
- name: Remove previous {{ test_subject }} output file
  file:
    path: /tmp/fluentbit-output.ndjson
    state: absent

- include_role:
    name: "{{ test_subject }}"
  vars:
    action: start

- name: Wait for port {{ subject_port }} to become available
  wait_for:
    port: "{{ subject_port }}"
    delay: 1

- name: Send test data
  shell: |
    echo "{\"log\":\"{\\\"message\\\":\\\"Hello world\\\"}\"}" | \
    socat -u - tcp:127.0.0.1:{{ subject_port }};

- include_role:
    name: "{{ test_subject }}"
  vars:
    action: stop

- name: Register {{ test_subject }} output
  shell: cat /tmp/fluentbit-output.ndjson
  register: output

- set_fact:
    first_message: "{{ output.stdout_lines[0]|from_json }}"

- assert:
    that:
      - first_message.message == "Hello world"
