logging.level: info

filebeat.inputs:
- type: tcp
  max_message_size: 10MiB
  host: "127.0.0.1:{{ subject_port }}"

processors:
  - decode_json_fields:
    fields: ["log"]
    process_array: false
    max_depth: 1
    target: ""
    overwrite_keys: true

# Due to filebeat's limited outputs, we choose logstash since it uses TCP.
# This is the simplest of outputs that lets us take the service down to
# enable buffering. This should work regardless of the use of their proprietary
# lumberjack protocol.
output.logstash:
  hosts: ["127.0.0.1:{{ tcp_consumer_port }}"]
