#!/bin/sh
#
# /etc/init.d/heka
# init script for heka.
#
# chkconfig: 2345 90 60
#
RETVAL=0

JARFILE="/opt/rizhiyi-agent/bin/forwarder-daemon.jar"
CONFIG="/opt/rizhiyi-agent/conf/daemon.config"

start() {
  /bin/echo Starting aixagent...
  nohup java -jar $JARFILE -config=$CONFIG > /dev/null 2>&1 &
  RETVAL=$?
}
stop() {
  /bin/echo Stopping aixagent...
  kill  `ps -aef | grep 'forwarder-daemon.jar' | grep -v grep | awk '{print $2}'`
  RETVAL=$?
}
restart() {
  stop
  start
  RETVAL=$?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    /bin/echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $RETVAL
