---
- import_playbook: reset.yml

- hosts: '{{ test_namespace }}:&tag_TestRole_subject'
  become: true
  tasks:
    - name: "Create {{ test_file_count }} test log files"
      include_role:
        name: flog
      vars:
        action: create_test_file
        bytes: 104857600
        location: "{{ test_file_location }}"
        encoding: text

    - name: Start test servers
      include_role:
        name: test_servers
      vars:
        action: start

    - name: Start {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: start

    - name: Wait 15 seconds
      pause:
        seconds: 15

    - name: Truncate file
      shell: truncate -s 0 {{ test_file_location }}

    - name: Add 1 line to the rotated file
      shell: echo "Hello world" >> {{ test_file_location }}

    - name: Wait 15 seconds
      pause:
        seconds: 15

    - name: Stop {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: stop

    - name: Stop test servers
      include_role:
        name: test_servers
      vars:
        action: stop

    - name: Capture last_message
      include: "capture_last_message/{{ test_subject }}.yml"

    - debug:
        var: last_message

    - assert:
        that:
          - last_message | search("Hello world")
