[sources.in]
  type = "docker"

[transforms.parse_json]
  inputs  = ["in"]
  type    = "json_parser"
  field   = "message"
  drop_invalid = false
  drop_field = true

[sinks.out]
  inputs   = ["parse_json"]
  type     = "socket"
  mode     = "tcp"
  address  = "127.0.0.1:{{ tcp_consumer_port }}"
  encoding = "text"
