---
- name: Install the http_test_server daemon systemd script
  template:
    src: http_test_server.service
    dest: /etc/systemd/system/http_test_server.service
    mode: 0644

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the http_test_server service is stopped
  systemd:
    name: http_test_server
    daemon_reload: yes
    enabled: no
    state: stopped
