---
- include_role:
    name: http_test_server
  vars:
    action: configure
    address: "{{ http_address }}"

- include_role:
    name: tcp_test_server
  vars:
    action: configure
    address: "{{ tcp_address }}"
