---
- include_role:
    name: file_test_server
  vars:
    action: install

- include_role:
    name: http_test_server
  vars:
    action: install

- include_role:
    name: tcp_test_server
  vars:
    action: install
