---
- include_role:
    name: file_test_server
  vars:
    action: start

- include_role:
    name: tcp_test_server
  vars:
    action: start_and_wait
    port: "{{ tcp_port }}"

- include_role:
    name: http_test_server
  vars:
    action: start_and_wait
    port: "{{ http_port }}"
