---
# Installs a Prometheus exporter archive from github.com/prometheus. Tested with node_exporter and haproxy_exporter, but
# would probably work with any exporters in the prometheus GH organization as they have consistent interfaces.
#
# By default, installs the node_exporter
- name: Download Prometheus {{ prometheus_exporter_name }} archive
  get_url:
    url: https://github.com/prometheus/{{ prometheus_exporter_name }}/releases/download/v{{ prometheus_exporter_version }}/{{ prometheus_exporter_name }}-{{ prometheus_exporter_version }}.linux-amd64.tar.gz
    # this checksum is _not_ a security check, it's merely to ensure we have the correct file (i.e., GitHub in its
    # infinite wisdom didn't barf up a 500)
    checksum: sha256:{{ prometheus_exporter_sha256 }}
    dest: /tmp/{{ prometheus_exporter_name }}.tar.gz
    mode: 0644

- name: Unarchive Prometheus {{ prometheus_exporter_name }} archive to /opt
  unarchive:
    dest: /opt
    remote_src: yes
    src: /tmp/{{ prometheus_exporter_name}}.tar.gz

- name: Remove Prometheus {{ prometheus_exporter_name }} archive
  file:
    path: /tmp/{{ prometheus_exporter_name }}.tar.gz
    state: absent

- name: Remove previous Prometheus directory
  file:
    path: /opt/prometheus_{{ prometheus_exporter_name }}
    state: absent

# This renames the directory to be version-less
- name: Rename Prometheus {{ prometheus_exporter_name }} directory
  command: mv /opt/{{ prometheus_exporter_name }}-{{ prometheus_exporter_version }}.linux-amd64 /opt/prometheus_{{ prometheus_exporter_name }}

# Install the systemd script
- name: Install Prometheus {{ prometheus_exporter_name }} systemd service
  template:
    src: exporter.service.j2
    dest: /etc/systemd/system/prometheus_{{ prometheus_exporter_name }}.service
    mode: 0644
    remote_src: no

# Enable the systemd unit file
- name: Enable Prometheus {{ prometheus_exporter_name }} systemd service
  systemd:
    name: prometheus_{{ prometheus_exporter_name }}
    daemon_reload: yes
    enabled: yes
