###Other
[RzyHttpInput]
address = ":{{ consumer_port }}"

[1_counter_filter]
type = "CounterFilter"
message_matcher = "Type != 'heka.counter-output'"
only_payload = true


[1_log_encoder]
type = "PayloadEncoder"

[1_log_output]
type = "LogOutput"
message_matcher = "Type == 'heka.counter-output'"
encoder = "1_log_encoder"

[hekad]
base_dir = "/opt/heka/cache/hekad"

###Output

[RzyFramingSplitter]

[RzyProtobufEncoder]
token = "87644362d6231a77d0373990fb61be74"
charset = ""
auto_conv = false

[RzyHttpOutput]
message_matcher = "{{ message_matcher }}"
address = "http://{{ consumer_ip }}:{{ consumer_port }}/proto/?compressed=false"
use_buffering = false
encoder = "RzyProtobufEncoder"
rate_limit = 0
[RzyHttpOutput.Buffering]
max_file_size = 268435456
max_buffer_size = 1073741824
full_action = "block"
cursor_update_count = 1000

