[sources.in]
  type               = "file"
  include            = ["{{ test_files_root }}*.log"]
  read_from          = "beginning"

[sinks.out]
  inputs                  = ["in"]
  type                    = "http"
  uri                     = "http://{{ consumer_ip }}:{{ consumer_port }}"
  encoding.codec                = "ndjson"
  batch.max_bytes          = 102400 # 100kib
  batch.timeout_secs      = 5
  request.rate_limit_num  = 10000

