[sources.in]
  type               = "file"
  include            = ["{{ test_files_root }}*.log"]
  start_at_beginning = true

[sinks.out]
  inputs                  = ["in"]
  type                    = "http"
  uri                     = "http://{{ consumer_ip }}:{{ consumer_port }}"
  encoding                = "ndjson"
  batch.max_size          = 102400 # 100kib
  batch.timeout_secs      = 5
  request.in_flight_limit = 10000
  request.rate_limit_num  = 10000

