---
- import_playbook: reset.yml

- hosts: '{{ test_namespace_subject }}'
  become: true
  tasks:
    - name: Start {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: start

    - name: Wait 5 seconds for {{ test_subject }} to initialize and warmup
      pause:
        seconds: 5

    - name: Wait 60 seconds for {{ test_subject }} to initialize and warmup
      pause:
        seconds: 60
      when: test_subject == 'logstash'

    - name: Start profiling {{ test_subject }}
      include_role:
        name: profiling
      vars:
        action: start

    - name: Wait 60 seconds for {{ test_subject }} to run
      pause:
        seconds: 60

    - name: Stop profiling {{ test_subject }}
      include_role:
        name: profiling
      vars:
        action: stop

    - name: Stop {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: stop
