---
# Creates the sslcerts group; this group will be given read
# permissions for ssl certificates and keys. This allows applications
# with non-root privileges to operate TLS connections.
# We specifically give GID 2001 so that it can be used with confd for
# setting the ownership of certificates
- name: Setup the sslcerts group
  group:
    name: sslcerts
    gid: 2001

- name: Setup the private SSL directory
  file:
    path: /etc/ssl/private
    state: directory
    owner: root
    group: sslcerts
    mode: 0710

# Install pre-defined FFDHE groups based on
# https://wiki.mozilla.org/Security/Server_Side_TLS#Pre-defined_DHE_groups
- name: Install Audited FFDHE group (2048 bit)
  copy:
    src: ffdhe2048.pem
    dest: /etc/ssl/ffdhe2048.pem
    owner: root
    group: sslcerts
    mode: 0644
    remote_src: no

- name: Install Audited FFDHE group (3072 bit)
  copy:
    src: ffdhe3072.pem
    dest: /etc/ssl/ffdhe3072.pem
    owner: root
    group: sslcerts
    mode: 0644
    remote_src: no

- name: Install Audited FFDHE group (4096 bit)
  copy:
    src: ffdhe4096.pem
    dest: /etc/ssl/ffdhe4096.pem
    owner: root
    group: sslcerts
    mode: 0644
    remote_src: no

# Installs the audited 2048 bit FFDHE group to /etc/ssl/private/dhparam.pem
# (which was previously generated using a call to openssl)
- name: Install Audited FFDHE group (2048 bit) as default DH param group
  copy:
    src: ffdhe2048.pem
    dest: /etc/ssl/private/dhparam.pem
    owner: root
    group: sslcerts
    mode: 0644
    remote_src: no
