---
- name: Install Rsyslog settings configuration
  template:
    src: "{{ configuration_file }}"
    dest: /etc/rsyslog.conf
    mode: 0644
  when: configuration_file != ""

- name: Install Rsyslog pipeline configuration
  template:
    src: "{{ pipeline_file }}"
    dest: /etc/rsyslog.d/rsyslog-test.conf
    mode: 0644
  when: pipeline_file != ""
