---
- import_playbook: reset.yml

- hosts: '{{ test_namespace }}'
  become: true
  tasks:
    - set_fact:
        consumer_role: "{% if test_subject=='heka' %}heka{% elif test_subject=='aixagent' %}heka{% elif test_subject=='logstash' %}logstash{% else %}http_test_server{% endif %}"

- hosts: '{{ test_namespace_consumer }}'
  become: true
  tasks:
    - name: Start consumer HTTP server
      include_role:
        name: "{{ consumer_role }}"
      vars:
        action: start
        server_port: "{{ consumer_port }}"

- hosts: '{{ test_namespace_subject }}'
  become: true
  tasks:
    - name: Wait for consumer {{ consumer_ip }}:{{ consumer_port }} to become available
      wait_for:
        host: "{{ consumer_ip }}"
        port: "{{ consumer_port }}"
        delay: 1

    - name: Start {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: start

    - name: Wait 5 seconds for {{ test_subject }} to initialize and warmup
      pause:
        seconds: 5

    - name: Wait 60 seconds for {{ test_subject }} to initialize and warmup
      pause:
        seconds: 60
      when: test_subject == 'logstash'

    - name: Start profiling {{ test_subject }}
      include_role:
        name: profiling
      vars:
        action: start

    - name: Wait 60 seconds for {{ test_subject }} to run
      pause:
        seconds: 60

    - name: Stop profiling {{ test_subject }}
      include_role:
        name: profiling
      vars:
        action: stop

    - name: Stop {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: stop

- hosts: '{{ test_namespace_consumer }}'
  become: true
  tasks:
    - name: Stop consumer HTTP server
      include_role:
        name: "{{ consumer_role }}"
      vars:
        action: stop
